homebridge-eufy-security/plugin

- src/accessories/LocalLivestreamCache.ts
- src/accessories/streamingDelegate.ts
> Added livestream cache for local streaming (no rtsp)

- homebridge-ui/public/index.html
- homebridge-ui/server.js
- src/accessories/LocalLivestreamManager.ts
- src/accessories/StationAccessory.ts
- Additional log output when station guard mode is changed (see #39)
- Edited description for livestream caching in configuration wizard
- #44  
_Added_ 2022-05-29:
- Bug where a local livestream cache may not have been shutdown properly and so subsequent livestreams would not be started
- Changed log output messages for better understanding
> Small additions and bugfix

- src/accessories/StationAccessory.ts
Handle alarm event that is triggered inside the Eufy APP
> Handle alarm event

- src/accessories/LocalLivestreamManager.ts
- src/accessories/StationAccessory.ts
- src/platform.ts
- possible fix for #56 
- changed a few debug messages
- possible better understanding of #52
> Clarification of some debug messages and possible fix for #56

- homebridge-ui/public/index.html
- src/accessories/CameraAccessory.ts
- src/accessories/LocalLivestreamManager.ts
- src/accessories/SnapshotManager.ts
- Sometimes motion events were not reset correctly, this will now be prevented
- minor bugs in new snapshot handling
- description in config wizard for snapshot handling
> Improvements to new snapshot handling

- src/accessories/CameraAccessory.ts
- src/accessories/SnapshotManager.ts
- src/accessories/streamingDelegate.ts
- Fix #48 Options enableCamera and enableMotion were not working in specific configuration situations
> Fix: #48 Enable Camera and Motion Buttons for Doorbell not working

- package.json
- src/platform.ts
- Preparation for talkback feature
- possible fix for #38
> updated dependency

- src/accessories/SnapshotManager.ts
- src/platform.ts
- support for Indoor Camera T8414
> Added support for indoor Camera T8414

- src/accessories/SmartLockAccessory.ts
- src/accessories/SnapshotManager.ts
* crash if first cloud snapshot could not be downloaded
* smart lock state could be wrong on startup
> Smartlock improvements

- CHANGELOG.md
- angular.json
- package-lock.json
- package.json
- src/configui/app/advanced-config-options/advanced-config-options.component.html
- src/configui/app/app.module.ts
- src/configui/app/config-options/download-logs/download-logs.component.html
- src/configui/app/config-options/download-logs/download-logs.component.ts
- src/configui/app/plugin.service.ts
- src/configui/environments/development/pluginUiMock.ts
- src/plugin/accessories/streamingDelegate.ts
- src/server.ts
- Download logs through configuration ui
- some users were unable to open configuration ui due to incorrect query of library version
- setting 'enable audio' was not working - audio was always streamed
> download logs feature

- .gitignore
- CHANGELOG.md
- src/plugin/utils/ffmpeg.ts
- Streams might have been aborted after 30-60 seconds due to stream backpressuring
> Fix aborted streaming

- CHANGELOG.md
- src/plugin/utils/ffmpeg.ts
- Minor bug that might have caused incorrect calculated output resolution
> minor fix for output resolution calculation

- .gitignore
- CHANGELOG.md
- src/plugin/utils/ffmpeg.ts
- Bug that caused faulty audio encoding parameters on certain codecs.
> minor bugfix

- .gitignore
- CHANGELOG.md
- src/configui/app/config-options/advanced-videoconfig/advanced-videoconfig.component.css
- src/configui/app/config-options/advanced-videoconfig/advanced-videoconfig.component.html
- src/configui/app/config-options/advanced-videoconfig/advanced-videoconfig.component.ts
- src/configui/app/config-options/config-options-interpreter.ts
- src/configui/app/config-options/enable-audio/enable-audio.component.html
- src/configui/app/config-options/enable-audio/enable-audio.component.ts
- src/configui/app/config-options/snapshot-handling-method/snapshot-handling-method.component.html
- src/plugin/accessories/CameraAccessory.ts
- src/plugin/accessories/DoorbellCameraAccessory.ts
- src/plugin/controller/SnapshotManager.ts
- src/plugin/controller/streamingDelegate.ts
- src/plugin/platform.ts
- src/plugin/utils/configTypes.ts
- src/plugin/utils/ffmpeg.ts
- src/server.ts
- Added additional audio settings in advanced video configuration
- Setting to choose custom path to ffmpeg executable.
- Improved verbose output for snapshot and ffmpeg processes
- Overhauled design of advanced video config
- Added explanatory description to snapshot handling method.
- Switches to turn camera and motion on/off should now be removed from HomeKit if the user switches the configuration
- Bug where no snapshot was returned after an event
> 2.2.0-beta.2

- CHANGELOG.md
- src/plugin/controller/SnapshotManager.ts
- Bug that caused a crash with node version prior to v14.18
> Bug that caused a crash with node version prior to v14.18

- CHANGELOG.md
- src/plugin/platform.ts
- src/plugin/utils/Talkback.ts
- Possible memory leak caused by not correctly released EventListeners
> Possible memory leak caused by not correctly released EventListeners

- CHANGELOG.md
- package-lock.json
- package.json
- Updated dependency to eufy-security-client@2.2.0-rc.1
> 2.2.0-beta.4 - update dependency

- CHANGELOG.md
- src/configui/app/accessory.service.ts
- src/configui/app/config-options/enable-hsv/enable-hsv.component.html
- src/configui/app/config-options/enable-hsv/enable-hsv.component.ts
- src/configui/app/config-options/snapshot-handling-method/snapshot-handling-method.component.html
- src/configui/app/config-options/snapshot-handling-method/snapshot-handling-method.component.ts
- src/plugin/accessories/StationAccessory.ts
- src/plugin/controller/LocalLivestreamManager.ts
- src/plugin/utils/EufyClientInteractor.ts
- src/plugin/utils/interfaces.ts
- src/server.ts
- Warn the user if multiple cameras are connected through the same station and limit critical options for these cameras (snapshot method and HKSV)
- Log errors in command results from eufy-security-client library to homebridge
- Removed overhead in stream processing improve performance
> 2.2.0-beta.5

- src/configui/app/login.service.ts
- src/configui/app/login/login.component.html
- src/configui/app/login/login.component.ts
- src/configui/app/util/types.ts
- src/plugin/config.ts
- src/plugin/platform.ts
- src/server.ts
> Fixed login issue

- src/plugin/accessories/CameraAccessory.ts
- src/plugin/accessories/SmartLockAccessory.ts
- src/plugin/platform.ts
- src/plugin/utils/EufyClientInteractor.ts
https://github.com/bropat/eufy-security-client/commit/5cdcf128c09c26417894019137b5364af3809565
> Tried fixing the breaking changes introduced in esc 2.2.3

- package-lock.json
- package.json
- src/configui/app/login.service.ts
- src/configui/app/login/login.component.html
- src/configui/app/login/login.component.ts
- src/configui/app/util/types.ts
- src/plugin/accessories/CameraAccessory.ts
- src/plugin/accessories/SmartLockAccessory.ts
- src/plugin/config.ts
- src/plugin/platform.ts
- src/server.ts
- Baurics fix for deviceName
- Updated Eufy Security Client to 2.2.3
- Updated Tslog to 3.3.4
- Fixing async breaking changes by ESC 2.2.3
> Bauric into master

- CHANGELOG.md
- package-lock.json
- package.json
- src/configui/app/config-options/enable-hsv/enable-hsv.component.html
- src/configui/app/config-options/enable-hsv/enable-hsv.component.ts
- src/configui/app/util/default-config-values.ts
- src/plugin/accessories/CameraAccessory.ts
- src/plugin/controller/recordingDelegate.ts
- src/plugin/utils/configTypes.ts
- src/plugin/utils/ffmpeg.ts
- Updated dependency: eufy-security-client to 2.3.0
- Added separate settings for HKSV encoding
> 2.2.0-beta.10

- CHANGELOG.md
- src/configui/app/advanced-config-options/advanced-config-options.component.html
- src/configui/app/app.module.ts
- src/configui/app/config-options/enable-hsv/enable-hsv.component.html
- src/configui/app/config-options/snapshot-handling-method/snapshot-handling-method.component.html
- src/configui/app/config-options/sync-station-modes/sync-station-modes.component.html
- src/configui/app/config-options/sync-station-modes/sync-station-modes.component.ts
- src/configui/app/util/default-config-values.ts
- src/plugin/accessories/StationAccessory.ts
- src/plugin/config.ts
- src/plugin/platform.ts
- Setting to sync the guard modes of all stations.
> 2.2.0-beta.13

- CHANGELOG.md
- src/configui/app/config-options/camera-buttons/camera-buttons.component.html
- src/configui/app/config-options/camera-buttons/camera-buttons.component.ts
- src/configui/app/config-options/talkback/talkback.component.html
- src/configui/app/config-options/talkback/talkback.component.ts
- src/configui/app/util/default-config-values.ts
- src/configui/app/util/eufy-security-client.utils.ts
- src/plugin/accessories/CameraAccessory.ts
- src/plugin/accessories/DoorbellCameraAccessory.ts
- src/plugin/accessories/StationAccessory.ts
- src/plugin/controller/streamingDelegate.ts
- src/plugin/utils/configTypes.ts
- src/plugin/utils/ffmpeg.ts
- Setting to add a switch to turn indoor chime on/off on some doorbells
- Setting for mono/stereo talkback configuration (needed for certain devices)
- Talkback was not working properly due to wrong channel configuration (can now be chosen: mono/stereo) #196
> 2.2.0-beta.14

- .github/workflows/dev_build_pr.yml
- .github/workflows/dev_npm_publish.yml
- .gitmodules
- CHANGELOG.md
- package-lock.json
- package.json
- src/server.ts
- eufy-security-client library is now added as forked dependency to enable direct changes
- Trying to fix login issue #250
> 2.2.0-beta.15

- .github/workflows/dev_build_pr.yml
- .github/workflows/dev_npm_publish.yml
- .gitmodules
- .npmignore
- CHANGELOG.md
- package-lock.json
- package.json
- eufy-security-client library is now added as forked dependency to enable direct changes
- Trying to fix login issue #250
- Fixed installation issues with previous betas
- Package size was dramatically reduced by removing cache files
> 2.2.0-beta.17

- package-lock.json
- package.json
- src/plugin/platform.ts
- src/server.ts
What's changed : 
- Display a message why plugin can't login because account as been flagged by Eufy Cloud
- Avoiding endless loop just to warn to use guest admin : warn and shutdown
> Warning default admin

- src/plugin/platform.ts
- src/server.ts
What's news : 
- Fix captcha and 2FA issue
- Fix tslog
> Fix captcha and 2FA issue and Fix tslog

- src/plugin/accessories/CameraAccessory.ts
What's new :
- [Append tampering to know that motion is altered because camera is disabled](https://github.com/homebridge-eufy-security/plugin/commit/c03b02b3e3b3e0d282b97cc0f95a8a214540a58e) 
- [Regression on enable/light/motion activation button (](https://github.com/homebridge-eufy-security/plugin/commit/f45658e420a432d3c9366bcb2152e77978e436a8)https://github.com/homebridge-eufy-security/plugin/issues/401 [thx](https://github.com/homebridge-eufy-security/plugin/commit/f45658e420a432d3c9366bcb2152e77978e436a8) @gmogoody[)](https://github.com/homebridge-eufy-security/plugin/commit/f45658e420a432d3c9366bcb2152e77978e436a8)
> Button motion

- CHANGELOG.md
- src/plugin/accessories/BaseAccessory.ts
- src/plugin/accessories/LockAccessory.ts
- **Added Debug Logs for Lock Status**
- Commit: 7d5d9e5
- Author: Lenoxys
- Date: Sun Sep 10 12:35:18 2023 +0200
- Description: Added extra debug information to understand lock status callbacks.
- **BaseAccessory.ts**
- Additional logging for `ON` state of characteristics.
- **LockAccessory.ts**
- Enhanced error message to include more details on lock state and errors.
- Minor comment update for clarity on lock status.
> Debug lock

- CHANGELOG.md
- src/plugin/accessories/LockAccessory.ts
- Adding missing characteristics to Lock Management
> Fixing lock issue

- CHANGELOG.md
- src/plugin/accessories/BaseAccessory.ts
- src/plugin/accessories/CameraAccessory.ts
- src/plugin/platform.ts
- `BaseAccessory.ts`: 
- Extended `getValue` and `setValue` to also accept `characteristic` and `service` as arguments.
- Removed some unnecessary lines of code.
- `CameraAccessory.ts`:
- Changed the method signatures for `getCameraPropertyValue` and `setCameraPropertyValue` to accommodate new characteristic arguments.
- Simplified and optimized logging and value updating processes.
> Updated method signatures in `BaseAccessory.ts` and `CameraAccessory.ts` to include new arguments, streamlined logging, and optimized value updating.

- src/plugin/accessories/CameraAccessory.ts
- Fixing getter and setter for camera properties
- @cixio, @julien94800 and @zhodd on issue #420 and #365
> Fixing getter and setter for camera properties

- CHANGELOG.md
- package-lock.json
- src/configui/app/config-options/camera-buttons/camera-buttons.component.html
- src/configui/app/config-options/camera-buttons/camera-buttons.component.ts
- src/configui/app/util/default-config-values.ts
- src/configui/app/util/eufy-security-client.utils.ts
- src/plugin/accessories/CameraAccessory.ts
- src/plugin/utils/configTypes.ts
- New feature to display HomeKit switch for indoor chime on/off (thanks @alternativ on #90)
- Updated systeminformation from 5.21.4 to 5.21.8 to address vulnerabilities
> Indoor chime button

- CHANGELOG.md
- src/configui/app/station-config-options/station-config-options.component.html
- src/plugin/accessories/BaseAccessory.ts
- src/plugin/accessories/StationAccessory.ts
- Unlocked the app-guard-modes-mapping component in the UI for station configuration options.
- Added helper functions for better configuration value selection in StationAccessory.ts.
- Modified and improved the convertHKtoEufy and convertEufytoHK methods to throw errors on invalid mode conversion.
> Station mode

- src/configui/app/accessory-list/accessory-list.component.html
- src/configui/app/accessory-list/accessory-list.component.ts
- src/configui/app/plugin.service.ts
- src/server.ts
- station/device list are not fully updated
- if a single device is attached to the station and they're not sharing the same serial number display it as a list
> [Bug]: if a single device is attached to the station and they're not sharing the same serial number display it as a list

- src/plugin/accessories/StationAccessory.ts
- When keypad attached to a station, modes wasn't applied properly
> [Bug]: missing state for "off"

- src/plugin/platform.ts
- Refactoring the way Stations and Devices are onboarded
- It will now display the type of the device when adding it into Apple Homekit
> Refactoring the way we onboard Stations and Devices

- src/configui/app/accessory-config-options/accessory-config-options.component.html
- src/configui/app/accessory-config-options/accessory-config-options.component.ts
- src/configui/app/accessory-list/accessory-list.component.html
- src/configui/app/config-options/ignore-accessory/ignore-accessory.component.ts
- src/configui/app/util/types.ts
- src/plugin/platform.ts
- src/server.ts
- **Improved Security Device Control Configuration**: Removed the ability to configure Security Device Control when not available with the Eufy Accessory, ensuring a more seamless user experience.
- **Streamlined Station Onboarding**: Refactored Station onboarding processes to eliminate reliance on manually updated static lists of types, now utilizing the ones provided by the library. This enhances efficiency and maintainability within the codebase.
- **Accessory Cleanup**: Removed station or device accessories created prior to plugin upgrade, which may have been subject to removal due to newly introduced logic. This ensures a cleaner and more consistent setup post-upgrade.
> Enhancements in Station Onboarding and Security Device Control Configuration

- src/configui/app/accessory-list/accessory-list.component.html
- src/configui/app/accessory-list/accessory-list.component.ts
- src/configui/app/util/types.ts
- src/server.ts
- Resolved issue where progress bar would block during the initial loading of stations or devices.
> Progress Bar Blocking on First Time Station/Device Loading

- src/configui/app/accessory-list/accessory-list.component.css
- src/configui/app/accessory-list/accessory-list.component.html
- src/configui/app/accessory-list/accessory-list.component.ts
- src/configui/app/login/login.component.html
- src/configui/app/login/login.component.ts
- src/server.ts
- UI Error when using a non GUEST ADMIN Account
- UI Warning when using NodeJS version which block streaming
> warn on using default admin account and using faultly NodeJS version

- src/configui/app/accessory-config-options/accessory-config-options.component.html
- src/configui/app/accessory-list/accessory-list.component.css
- src/configui/app/accessory-list/accessory-list.component.html
- src/configui/app/config-options/ignore-accessory/ignore-accessory.component.html
- src/configui/app/config-options/ignore-accessory/ignore-accessory.component.ts
- src/configui/app/util/types.ts
- src/configui/main.ts
- src/server.ts
- Prevent when keypad is detected
> Prevent when keypad is used

- src/plugin/platform.ts
- Removing keypad from Apple HK
> [Bug]:  Keypad (T8960) not supported

- src/server.ts
Restructure the server initialization process to improve clarity and efficiency, while enhancing the handling of asynchronous operations.
> Refactor server initialization and enhance async handling

- package-lock.json
- src/plugin/controller/SnapshotManager.ts
- src/plugin/controller/streamingDelegate.ts
- src/plugin/utils/utils.ts
- src/server.ts
Enhance server closing logic for better resource cleanup, optimize snapshot resizing to prevent unnecessary instantiation, and streamline logging in stream request handling for improved clarity. Update Node.js engine version compatibility in the package-lock.json.
> Improve server logic, optimize snapshot handling, and enhance logging
